//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusyPlace
    {
        public int ID { get; set; }
        public int IDPlace { get; set; }
        public int IDSession { get; set; }
        public bool IsBusy { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Session Session { get; set; }
    }
}
