//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MG_KISHEntities1 : DbContext
    {
        public MG_KISHEntities1()
            : base("name=MG_KISHEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book> book { get; set; }
        public virtual DbSet<BookGanre> BookGanre { get; set; }
        public virtual DbSet<ganre> ganre { get; set; }
        public virtual DbSet<readList> readList { get; set; }
        public virtual DbSet<readStatus> readStatus { get; set; }
        public virtual DbSet<report> report { get; set; }
        public virtual DbSet<requestRole> requestRole { get; set; }
        public virtual DbSet<requestUnFreeze> requestUnFreeze { get; set; }
        public virtual DbSet<review> review { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<user_> user_ { get; set; }
    }
}
