//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int ID { get; set; }
        public int userID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> reviewID { get; set; }
        public System.DateTime reportDate { get; set; }
    
        public virtual book book { get; set; }
        public virtual review review { get; set; }
        public virtual user_ user_ { get; set; }
    }
}
