//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class requestRole
    {
        public int ID { get; set; }
        public int userID { get; set; }
        public string requestText { get; set; }
        public System.DateTime reportDate { get; set; }
    
        public virtual user_ user_ { get; set; }
    }
}
